
export const CHANGE_PLAYLIST = "CHANGE_PLAYLIST";

export const CHANGE_SONGINDEX = "CHANGE_SONGINDEX";

export const CHANGE_SONG = "CHANGE_SONG";

export const CHANGE_SEQUENCE = "CHANGE_SEQUENCE"

export const CHANGE_LYRIC = "CHANGE_LYRIC"

export const CHANGE_LYRICINDEX = "CHANGE_LYRICINDEX"
